- name: import variable check tasks (lynis)
  import_tasks: checks.yml
  tags:
    - monitoring
    - lynis

- name: import lynis setup tasks
  become: true
  import_tasks: lynis.yml
  when: setup_lynis | bool
  tags:
    - monitoring
    - lynis

- name: import lynis uninstallation tasks
  become: true
  import_tasks: lynis-uninstall.yml
  when: not setup_lynis | bool
  tags:
    - monitoring
    - lynis
